// <auto-generated />
namespace Refma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201505082041584_changedmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
